[package]
name = "rc5"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
byteorder = "1.4.3"
hex = "0.4.3"